// Vimberman — level data
// Legend: # wall  % rock  & hard rock  . floor  ~ gap  <>^v one-way (arrow = only
// direction of travel allowed when entering)  a-z lettered tiles  * bush  E exit
// P player  Z zombie  I imp  M mage  T code-tile (terminal)

const LEVELS = [
  {
    name: 'BABY STEPS',
    teaches: 'h j k l',
    intro: [
      'Move with  h (left)  j (down)  k (up)  l (right).',
      'Arrow keys are for tourists. Reach the exit  E .',
      'Walk over bushes * — they hide useful things.',
    ],
    map: [
      '#############',
      '#P....#.....#',
      '#.###.#.###.#',
      '#.#...#...#.#',
      '#.#.#####.#.#',
      '#.#.....#.#.#',
      '#.###.#.#.#.#',
      '#*....#...#E#',
      '#############',
    ],
    terminals: {},
    bushes: { '1,7': { type: 'K', amt: 10 } },
    par: 40, limit: 110,
  },
  {
    name: 'COUNT THE CORRIDORS',
    teaches: 'counts: 10l 6j',
    intro: [
      'Prefix a motion with a number:  10l  moves ten right,',
      '6j  drops six down — one action, one enemy step.',
      'A zombie shambles after you. Every wasted key feeds it.',
    ],
    map: [
      '#############',
      '#P..........#',
      '#.#########.#',
      '#.....*.....#',
      '#.#########.#',
      '#.....*.....#',
      '#.#########.#',
      '#Z........E.#',
      '#############',
    ],
    terminals: {},
    bushes: { '6,3': { type: 'K', amt: 8 }, '6,5': { type: 'U', amt: 1 } },
    par: 9, limit: 26,
  },
  {
    name: 'LEAP OF FAITH',
    teaches: 'f{char} F{char} — dash to a letter',
    intro: [
      'f then a letter dashes RIGHT to that lettered tile,',
      'F dashes LEFT — and a dash flies clean over gaps.',
      't / T land one tile short. Mind the imp.',
    ],
    map: [
      '#############',
      '#P..~~~a....#',
      '#######.#####',
      '#b~~~...*..I#',
      '#.###########',
      '#..~~~c~~~d.#',
      '###########.#',
      '#Ee~~~~~f...#',
      '#############',
    ],
    terminals: {},
    bushes: { '8,3': { type: 'U', amt: 1 } },
    enemyOpts: { '11,3': { leash: 'row' } },
    par: 30, limit: 75,
  },
  {
    name: 'BUGFIX BOMBS',
    teaches: 'i x r — edit words, earn bombs',
    intro: [
      'Stand on a code-tile T and press  i  to open it.',
      'Fix the broken word:  x deletes a char,  r{char} replaces one.',
      'A fixed word arms a bomb. Drop it with  x , then RUN —',
      'the blast is a big plus shape. Rocks % crumble. So do you.',
    ],
    map: [
      '#############',
      '#P....#.....#',
      '#.###.#.%.#*#',
      '#.#T..#.#.#.#',
      '#.#####.#.###',
      '#.%...#.#*###',
      '#.#.#.#.#####',
      '#.#.#..ZT%.E#',
      '#############',
    ],
    terminals: {
      '3,3': { broken: 'bpmb', target: 'bomb', grants: 1, hint: 'l  ro' },
      '8,7': { broken: 'boamb', target: 'bomb', grants: 1, hint: '2l  x' },
    },
    bushes: { '11,2': { type: 'B', amt: 1 }, '9,5': { type: 'U', amt: 1 } },
    par: 62, limit: 135,
  },
  {
    name: 'WORD BRIDGES',
    teaches: 'w b e — hop between words',
    intro: [
      'Adjacent lettered tiles form WORDS.',
      'w hops to the next word start, b hops back, e to a word end —',
      'soaring over gaps and even over enemies.',
    ],
    map: [
      '#############',
      '#P.vim~~~ed.#',
      '###########.#',
      '#..tip~~go.*#',
      '#.###########',
      '#.Ican~~~elf#',
      '###########.#',
      '#E.zag~~~ox.#',
      '#############',
    ],
    terminals: {},
    bushes: { '11,3': { type: 'K', amt: 12 } },
    enemyOpts: { '2,5': { leash: 'row' } },
    par: 26, limit: 60,
  },
  {
    name: 'THE LONG WAY',
    teaches: '0 $ gg G — slam across lines',
    intro: [
      '0 slides to the row start, $ to its end.',
      'gg slams to the top of your column, G to the bottom.',
      'Slides sweep up items on the way and stop at trouble.',
    ],
    map: [
      '###############',
      '#P#...#...#...#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#*#T#.#%#Z#*#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#...#...#...#E#',
      '###############',
    ],
    terminals: {
      '5,5': { broken: 'bo0mb', target: 'bomb', grants: 2, hint: '2l  x' },
    },
    bushes: { '3,5': { type: 'K', amt: 10 }, '13,5': { type: 'U', amt: 1 } },
    par: 55, limit: 115,
  },
  {
    name: 'REWRITE THE RULES',
    teaches: 'cw — change a whole word',
    intro: [
      'Some words are beyond repair.  cw  wipes from the cursor',
      'to the word end and drops you into INSERT mode —',
      'type the new word, then  Esc  to commit it.',
    ],
    map: [
      '#############',
      '#P..#...#..*#',
      '#.#.#.#.#.#.#',
      '#.#.#I#.#.#.#',
      '#T#.%.#.%.#.#',
      '#.#.#.#.#Z#.#',
      '#.#.#.#.#.#.#',
      '#..*#..T#..E#',
      '#############',
    ],
    terminals: {
      '1,4': { broken: 'dud', target: 'bomb', grants: 1, hint: 'cw bomb Esc' },
      '7,7': { broken: 'fizz', target: 'bomb', grants: 1, hint: 'cw bomb Esc' },
    },
    bushes: { '3,7': { type: 'U', amt: 1 }, '11,1': { type: 'B', amt: 1 } },
    enemyOpts: { '5,3': { leash: 'col' }, '9,5': { leash: 'col' } },
    par: 80, limit: 140,
  },
  {
    name: 'AGAINST THE CURRENT',
    teaches: 'one-way tiles — commit or route around',
    intro: [
      'Arrow tiles < > ^ v only let you enter moving that way.',
      'Once you drop through a  v  there is no climbing back.',
      'Everything you know. Plan the whole loop before you jump.',
    ],
    map: [
      '###############',
      '#P~~~cat~~~ed*#',
      '#############.#',
      '#.fix~~~onI.#.#',
      '#.#########.#.#',
      '#.###..E..#.#.#',
      '#.#####^###.#.#',
      '#.#<<<<.<<<.#.#',
      '#.###########V#',
      '#.*.%..Z.T....#',
      '###############',
    ],
    terminals: {
      '9,9': { broken: 'dirt', target: 'bomb', grants: 2, hint: 'cw bomb Esc' },
    },
    bushes: { '13,1': { type: 'B', amt: 1 }, '2,9': { type: 'R', amt: 1 } },
    enemyOpts: { '10,3': { leash: 'row' } },
    par: 75, limit: 130,
  },
  {
    name: 'WARPED WORDS',
    teaches: '~ and ciw — case flips, inner words',
    intro: [
      '~ toggles the case under the cursor and steps right.',
      'ciw wipes the whole word you are inside, from anywhere in it.',
      'A mage now blinks around you. Never linger in its row.',
      'Hard rock & only cracks under a widened blast — find the bush.',
    ],
    map: [
      '###############',
      '#P.~~~jam~~ox*#',
      '#############.#',
      '#.....T.M..<<.#',
      '#%#############',
      '#....&.E#######',
      '#.#############',
      '#.>..T..*..>..#',
      '#.###########.#',
      '#..Z....*.....#',
      '###############',
    ],
    terminals: {
      '6,3': { broken: 'BOMB', target: 'bomb', grants: 1, hint: '~~~~' },
      '5,7': { broken: 'zzzz', target: 'bomb', grants: 2, hint: 'ciw bomb Esc' },
    },
    bushes: {
      '13,1': { type: 'K', amt: 10 },
      '8,7': { type: 'R', amt: 1 },
      '8,9': { type: 'U', amt: 1 },
    },
    enemyOpts: { '3,9': { leash: 'row' } },
    par: 105, limit: 160,
  },
  {
    name: 'THE FINAL REFACTOR',
    teaches: 'everything — and a merciless budget',
    intro: [
      'No new tricks. No slack in the budget.',
      'Zombie, imp and mage between you and the vault.',
      'Golf it. Every keystroke is ammunition.',
    ],
    map: [
      '###############',
      '#P~~vim~~~goT.#',
      '#############V#',
      '#.Z..I.....<<.#',
      '#.#####%#######',
      '#.#####*#######',
      '#.#############',
      '#.#########E###',
      '#.#########^###',
      '#..MT...&...*.#',
      '###############',
    ],
    terminals: {
      '12,1': { broken: 'b0mB', target: 'bomb', grants: 2, hint: 'l ro  2l ~' },
      '4,9': { broken: 'rusty', target: 'bomb', grants: 1, hint: 'ciw bomb Esc' },
    },
    bushes: { '7,5': { type: 'R', amt: 1 }, '12,9': { type: 'U', amt: 1 } },
    enemyOpts: { '2,3': { leash: 'row' }, '5,3': { leash: 'row' } },
    par: 115, limit: 175,
  },
];

if (typeof module !== 'undefined') module.exports = { LEVELS };
