// Vimberman — level data
// Legend: # wall  % rock  & hard rock  . floor  ~ gap  <>^V one-way (arrow = only
// direction of travel allowed when entering)  a-z lettered tiles  * bush  E exit
// P player  Z zombie  I imp  M mage  Q toad  T code-tile (terminal)
// ? keycap (motion unlock)  ! linter emitter (in wall)  | margin  @ updraft
// ()[]{} paired bracket doors (% jumps between partners; 0-or-2 per kind)
// A level's `sky` array is the cloud layer, same size as `map`.
import type { LevelDef } from './engine/types';

export const LEVELS: LevelDef[] = [
  {
    name: 'BABY STEPS',
    teaches: 'h j k l',
    intro: [
      'Move with  h (left)  j (down)  k (up)  l (right).',
      'Arrow keys are for tourists. Reach the exit  E .',
      'Walk over bushes * — they hide useful things.',
    ],
    map: [
      '#############',
      '#P....#.....#',
      '#.###.#.###.#',
      '#.#...#...#.#',
      '#.#.#####.#.#',
      '#.#.....#.#.#',
      '#.###.#.#.#.#',
      '#*....#...#E#',
      '#############',
    ],
    terminals: {},
    bushes: { '1,7': { type: 'K', amt: 10 } },
    gutter: false,
    hint: 'the maze has exactly one shape. walk it like you mean it.',
    solution: 'jjjjjj llll kk ll jj ll kk kk hh kk llll jjjjjj',
    par: 40, limit: 110,
  },
  {
    name: 'COUNT THE CORRIDORS',
    teaches: 'counts: 10l 6j',
    intro: [
      'Grab the keycap ? — it teaches your fingers to COUNT.',
      'Prefix a motion with a number:  9l  moves nine right,',
      '6j  drops six down — one action, one enemy step.',
      'The margin numbers count the distance for you. See 6? Type 6j.',
    ],
    map: [
      '#############',
      '#P?.........#',
      '#.#########.#',
      '#.....*.....#',
      '#.#########.#',
      '#.....*.....#',
      '#.#########.#',
      '#Z........E.#',
      '#############',
    ],
    terminals: {},
    bushes: { '6,3': { type: 'K', amt: 8 }, '6,5': { type: 'U', amt: 1 } },
    keycaps: { '2,1': 'count' },
    hint: 'a zombie moves once per completed command. count, don\'t tap.',
    solution: 'l 9l 6j h',
    par: 9, limit: 26,
  },
  {
    name: 'LEAP OF FAITH',
    teaches: 'f F t ; — dash, stop short, repeat',
    intro: [
      'f then a letter dashes RIGHT to that lettered tile,',
      'F dashes LEFT — and a dash flies clean over gaps.',
      't / T land one tile short: sometimes the door is BESIDE',
      'the letter. ; repeats your last dash — these rows rhyme.',
    ],
    map: [
      '#############',
      '#P?.~~.a....#',
      '######.######',
      '#b~~~...*..I#',
      '#.###########',
      '#..~~~c~~~.c#',
      '###########.#',
      '#Ef~~~~~f...#',
      '#############',
    ],
    terminals: {},
    bushes: { '8,3': { type: 'U', amt: 1 } },
    enemyOpts: { '11,3': { leash: 'row' } },
    keycaps: { '2,1': 'find' },
    hint: 'the shaft sits one short of the a. the c and the f both echo.',
    solution: 'll ta jj 2l Fb jj fc ; jj Ff ; h',
    par: 21, limit: 52,
  },
  {
    name: 'BUGFIX BOMBS',
    teaches: 'i x r — edit words, earn bombs',
    intro: [
      'Stand on a code-tile T and press  i  to open it.',
      'Fix the broken word:  x deletes a char,  r{char} replaces one.',
      'A fixed word arms a bomb. Drop it with  x , then RUN —',
      'the blast is a big plus shape. Rocks % crumble. So do you.',
    ],
    map: [
      '#############',
      '#P?...#.....#',
      '#.###.#.%.#*#',
      '#.#T..#.#.#.#',
      '#.#####.#.###',
      '#.%...#.#*###',
      '#.#.#.#.#####',
      '#.#.#..ZT%.E#',
      '#############',
    ],
    terminals: {
      '3,3': { broken: 'bpmb', target: 'bomb', grants: 1, hint: 'l  ro' },
      '8,7': { broken: 'boamb', target: 'bomb', grants: 1, hint: '2l  x' },
    },
    bushes: { '11,2': { type: 'B', amt: 1 }, '9,5': { type: 'U', amt: 1 } },
    keycaps: { '2,1': 'edit' },
    hint: 'the fuse is six turns. plan the exit before you light it.',
    solution: '4l jj hh i l ro ll kk 4h 4j x kkk h h 3j 4k h h h 4j 4l jj ll l i ll x h x h h k l l l j 6l',
    par: 62, limit: 135,
  },
  {
    name: 'WORD BRIDGES',
    teaches: 'w b e — hop between words',
    intro: [
      'Adjacent lettered tiles form WORDS.',
      'w hops to the next word start, b hops back, e to a word end —',
      'soaring over gaps and even over enemies.',
      'Three roads to the exit. Pick a personality.',
    ],
    map: [
      '###############',
      '#P?.vim~~~ed..#',
      '#.#.#########.#',
      '#?#.be~~ta..#.#',
      '#*#.#######.#.#',
      '#.#....*....#.#',
      '#.#########.#.#',
      '#.*Ican~~go.E.#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '1,4': { type: 'K', amt: 8 },
      '7,5': { type: 'K', amt: 10 },
      '2,7': { type: 'U', amt: 1 },
    },
    enemyOpts: { '3,7': { leash: 'row' } },
    keycaps: { '2,1': 'word', '1,3': 'word' },
    hint: 'a naive w lands where the imp lives. a counted 2w does not.',
    solution: 'l 2w 3l 6j h',
    par: 8, limit: 18,
  },
  {
    name: 'THE LONG WAY',
    teaches: '0 $ gg G — slam across lines',
    intro: [
      '0 slides to the row start, $ to its end.',
      'gg slams to the top of your column, G to the bottom.',
      'Slides sweep up items on the way and stop at trouble.',
      'A second tile is lint-infested: inside a tile, f{char} dashes, x deletes.',
    ],
    map: [
      '###############',
      '#P#...#...#...#',
      '#?#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#*#T#T#%#Z#*#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#.#.#.#.#.#.#.#',
      '#...#...#...#E#',
      '###############',
    ],
    terminals: {
      '5,5': { broken: 'bo0mb', target: 'bomb', grants: 2, hint: '2l  x' },
      // purging the lint arms you with a linter of your own (docs/arsenal.md)
      '7,5': { kind: 'clean', broken: 'bomb(##);', grants: 1, arms: 'grep', hint: 'f#  xx' },
    },
    bushes: { '3,5': { type: 'K', amt: 10 }, '13,5': { type: 'U', amt: 1 } },
    enemyOpts: { '11,5': { phase: 1 } },
    keycaps: { '1,2': 'line' },
    hint: 'the comb has teeth. gg and G are how you bite back.',
    solution: 'j G ll gg ll 4j i ll x G ll gg ll G x gg l l l l l G ll l l l l l l l l l l l x h h gg l l l G ll gg ll G',
    par: 60, limit: 118,
  },
  {
    name: 'FLIP THE SCRIPT',
    teaches: 'flight flips toads',
    intro: [
      'Toads hop two tiles every third turn — over gaps, at you.',
      'FLY over one (w, e, f) and it lands on its back, helpless,',
      'for six turns. Walk onto a flipped toad to squash it: +2 keys.',
      'Walking around a toad is how you lose. Fly.',
    ],
    map: [
      '###############',
      '#P..hop~Q~it..#',
      '#.#.#########.#',
      '#.#.no~Q~go.#.#',
      '#*#.#######.#.#',
      '#.#..Q..*...#.#',
      '#.#########.#.#',
      '#.*.up~Q~on.E.#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '1,4': { type: 'K', amt: 6 },
      '8,5': { type: 'K', amt: 8 },
      '2,7': { type: 'U', amt: 1 },
    },
    enemyOpts: { '7,7': { leash: 'row' } },
    hint: 'the toad crosses pits. so do you. only one of you flips.',
    solution: 'll 2w 3l 6j h',
    par: 9, limit: 22,
  },
  {
    name: 'REWRITE THE RULES',
    teaches: 'cw — change a whole word',
    intro: [
      'Some words are beyond repair.  cw  wipes from the cursor',
      'to the word end and drops you into INSERT mode —',
      'type the new word, then  Esc  to commit it.',
      'A coin cache hums in the west wall: land on every o',
      'before its clock runs out, or the coins respawn.',
      'Two gates, three terminals, three ways through. Choose.',
    ],
    map: [
      '###############',
      '#P?.ab~~~~cd..#',
      '#?..#.....#...#',
      '#.T.#..T..##%##',
      '#...#.....#...#',
      '#T..%..Z..%...#',
      '#...#.*.*.#...#',
      '#...#.....#..E#',
      '###############',
    ],
    terminals: {
      '2,3': { broken: 'dud', target: 'bomb', grants: 1, hint: 'cw bomb Esc' },
      // the pacifist's key: sed digs but never kills — and it's a shorter edit
      '7,3': { broken: 'fizz', target: 'sed', grants: 2, hint: 'cw sed Esc' },
      '1,5': { kind: 'coins', broken: '.o..o..o', deadline: 6, grants: 1, hint: 'l 3l 3l — spam loses' },
    },
    bushes: { '6,6': { type: 'K', amt: 10 }, '8,6': { type: 'U', amt: 1 } },
    enemyOpts: { '7,5': { leash: 'col' } },
    keycaps: { '2,1': 'cw', '1,2': 'cw' },
    hint: 'the plug above E cracks from the lobby. you never need the zombie.',
    solution: 'jj l i cw bomb <e> kk w w 3l j h x l k l l l j h j 4j l',
    par: 32, limit: 65,
  },
  {
    name: 'AGAINST THE CURRENT',
    teaches: 'one-way tiles — commit or route around',
    intro: [
      'Arrow tiles < > ^ v only let you enter moving that way.',
      'Once you drop through a  v  there is no climbing back.',
      'Everything you know. Plan the whole loop before you jump.',
    ],
    map: [
      '###############',
      '#P~~~cat~~~ed*#',
      '#############.#',
      '#.fix~~~onI.#.#',
      '#.#########.#.#',
      '#.###..E..#.#.#',
      '#.#####^###.#.#',
      '#.#<<<<.<<<.#.#',
      '#.###########V#',
      '#.*.%..Z.T....#',
      '###############',
    ],
    terminals: {
      '9,9': { broken: 'dirt', target: 'bomb', grants: 2, hint: 'cw bomb Esc' },
    },
    bushes: { '13,1': { type: 'B', amt: 1 }, '2,9': { type: 'R', amt: 1 } },
    enemyOpts: { '10,3': { leash: 'row' } },
    hint: 'the chute is a promise. read the bottom row before you keep it.',
    solution: 'w w ll 7j l l l l l l l x 3k l l l l l 4j hhhh i cw bomb <e> hhhh x lll j j 7h gg w j j w k x b j j j j w lll 4j hhhh k k',
    par: 73, limit: 130,
  },
  {
    name: 'MIND THE MARGINS',
    teaches: '0 $ — anchors when the row goes hot',
    intro: [
      'The lamp ! lints its whole row on a six-turn cycle:',
      'three dark, two amber, then the SWEEP. Everything standing',
      'in the row dies — except on the margins | at its ends.',
      '0 and $ snap you to a margin from anywhere. No counting.',
    ],
    map: [
      '###############',
      '#P.....*.....*#',
      '#.###########.#',
      '!|.*.....*...|#',
      '#######.#######',
      '#......*......#',
      '###.#######.###',
      '!|...*....*..|#',
      '#.###########.#',
      '#E....*.......#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '7,1': { type: 'K', amt: 6 },
      '13,1': { type: 'U', amt: 1 },
      '3,3': { type: 'K', amt: 8 },
      '9,3': { type: 'K', amt: 8 },
      '5,7': { type: 'K', amt: 6 },
      '10,7': { type: 'K', amt: 8 },
      '6,9': { type: 'K', amt: 5 },
    },
    linters: { '0,3': {}, '0,7': { phase: 3 } },
    hint: 'when the lamp blinks amber you have two turns. $ is one keystroke.',
    solution: 'jj 2l 4l jj 4h jj 0 jj',
    par: 15, limit: 34,
  },
  {
    name: 'WARPED WORDS',
    teaches: '~ and ciw — case flips, inner words',
    intro: [
      '~ toggles the case under the cursor and steps right.',
      'ciw wipes the whole word you are inside, from anywhere in it.',
      'A mage now blinks around you. Never linger in its row.',
      'Hard rock & only cracks under a widened blast — find the bush.',
      'The south-east tile is a GOLF tile: one stroke, or it resets.',
    ],
    map: [
      '###############',
      '#P?~~~jam~~ox*#',
      '#############.#',
      '#.....T.M..<<.#',
      '#%#############',
      '#....&.E#######',
      '#.#############',
      '#.>..T..*..>..#',
      '#.###########.#',
      '#..Z....*...T.#',
      '###############',
    ],
    terminals: {
      '6,3': { broken: 'BOMB', target: 'bomb', grants: 1, hint: '~~~~' },
      '5,7': { broken: 'zzzz', target: 'bomb', grants: 2, hint: 'ciw bomb Esc' },
      '12,9': { kind: 'golf', broken: 'Bomb', target: 'bomb', strokes: 1, grants: 1, hint: 'one stroke. you know the one.' },
    },
    bushes: {
      '13,1': { type: 'K', amt: 10 },
      '8,7': { type: 'R', amt: 1 },
      '8,9': { type: 'U', amt: 1 },
    },
    enemyOpts: { '3,9': { leash: 'row' } },
    keycaps: { '2,1': 'inner' },
    hint: 'the mage never ports onto your row. so keep changing rows.',
    solution: 'w w ll jj l l l l hh hhh hh i ~~~~ hhhhh x llll k k hhhh j 3j l ll l i ciw bomb <e> lll ll l ll jj l l hhhh j j j j j j j j h x llll j j 7h hhhh 4k lll x hhh k h h j 5l l',
    par: 112, limit: 165,
  },
  {
    name: 'HEAD IN THE CLOUDS',
    teaches: 'Ctrl-u Ctrl-d — the sky layer',
    intro: [
      'An updraft @ plus Ctrl-u lifts you into the clouds.',
      'Up there nothing hunts you — but nothing explodes either.',
      'Arrows in the clouds are WIND: every turn you stand in one,',
      'it carries you a tile. And the zombies still gather under',
      'your shadow. A bomb left behind makes that their problem.',
    ],
    map: [
      '###############',
      '#P?*.@...Z...*#',
      '#.###########.#',
      '#....Z........#',
      '#.###########.#',
      '#...Z....*....#',
      '#############.#',
      '#E....@..Z....#',
      '###############',
    ],
    sky: [
      '###############',
      '#....@..nim...#',
      '#.............#',
      '#..##......##.#',
      '#.............#',
      '#..##......##.#',
      '#.............#',
      '#..*<<........#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '3,1': { type: 'B', amt: 1 },
      '13,1': { type: 'K', amt: 6 },
      '9,5': { type: 'K', amt: 8 },
      'sky:3,7': { type: 'K', amt: 10 },
    },
    keycaps: { '2,1': 'sky' },
    hint: 'the river flows toward the exit. the bomb flies nowhere — leave it.',
    solution: 'l 3l <C-u> 6j 3h <C-d>',
    par: 9, limit: 26,
  },
  {
    name: 'CUMULUS GOLF',
    teaches: 'kites — flight cuts the string',
    intro: [
      'A kite rides the middle air. Full speed, never blinks, and',
      'only thunderheads slow it down. Fly over it — f, w, t —',
      'and the string is cut. Or time its patrol and slip past.',
      'The exit is up there too. Nothing says you must come down.',
    ],
    map: [
      '###############',
      '#P..@#...@.####',
      '#.*..#*.*.*####',
      '###############',
    ],
    sky: [
      '###############',
      '#....##......E#',
      '#......cu.Y.t.#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '2,2': { type: 'K', amt: 4 },
      '6,2': { type: 'K', amt: 6 },
      '8,2': { type: 'K', amt: 8 },
      '10,2': { type: 'U', amt: 1 },
    },
    enemyOpts: { '10,2': { leash: 'col' } },
    hint: 'the word is c-u-t. the last dash is the scissors.',
    solution: '3l <C-u> j fc ft k l',
    par: 10, limit: 30,
  },
  {
    name: 'BOOKMARKED',
    teaches: 'm{a} `{a} — bookmarks',
    intro: [
      'm then a letter drops a bookmark. Free — thinking costs nothing.',
      'Backtick then the letter jumps you straight back to it.',
      'The vault below holds the only bomb. The vault has no stairs.',
      'Mark before you drop. And know this: explosions eat bookmarks.',
    ],
    map: [
      '###############',
      '#P?...........#',
      '#.#.#V###.#.#%#',
      '#.*.#*.*#.Z*#E#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '2,3': { type: 'U', amt: 1 },
      '5,3': { type: 'B', amt: 1 },
      '7,3': { type: 'K', amt: 8 },
      '11,3': { type: 'K', amt: 6 },
    },
    enemyOpts: { '10,3': { leash: 'row' } },
    keycaps: { '2,1': 'mark' },
    hint: 'the vault is a promise to your future self. mark first, fall second.',
    solution: 'l 11l ma 8h 2j `a x 2h j j k h k 2l 2j',
    par: 22, limit: 52,
  },
  {
    name: 'BALANCED BRACKETS',
    teaches: '% — jump to the matching bracket',
    intro: [
      'Brackets come in pairs. Stand on one, press  %  — you are',
      'at its partner. Instantly. Both directions. No questions.',
      'The bomb closet has one door, and your blast will fill it.',
      'A lint zombie sweeps the exit row. f and w still matter.',
    ],
    map: [
      '###############',
      '#P?[....)...#]#',
      '#.###########*#',
      '#.>*T(.%>okZE##',
      '###############',
    ],
    terminals: {
      '4,3': { broken: 'b(mb', target: 'bomb', grants: 1, hint: 'l ro' },
    },
    bushes: {
      '3,3': { type: 'U', amt: 1 },
      '13,2': { type: 'K', amt: 10 },
    },
    enemyOpts: { '11,3': { leash: 'row' } },
    keycaps: { '2,1': 'match' },
    hint: 'the closet bracket is a door out. the corridor bracket is a door in.',
    solution: 'l h 2j l 2l i l ro l x % 5h % j k % 2h 2j l fE',
    par: 27, limit: 62,
  },
  {
    name: 'GREP',
    teaches: '/{word} n — search the whole file',
    intro: [
      '/ then a word, then Enter — you are AT that word. Anywhere.',
      'n repeats the jump to the next match, wrapping around.',
      'Typing in the prompt is free. Thinking always is.',
      'The moats have no bridges. The word "bug" appears four times.',
    ],
    map: [
      '###############',
      '#P?..bug....*.#',
      '#.....~~......#',
      '#..Z.....bug..#',
      '#~~~~~~~~~~~~~#',
      '#..bug..*.I...#',
      '#~~~~~~~~~~~~~#',
      '#.*..bug....E.#',
      '###############',
    ],
    terminals: {},
    bushes: {
      '12,1': { type: 'K', amt: 6 },
      '8,5': { type: 'U', amt: 1 },
      '2,7': { type: 'K', amt: 5 },
    },
    enemyOpts: { '10,5': { leash: 'row' } },
    keycaps: { '2,1': 'search' },
    hint: 'four bugs, one query. the moat was never the obstacle.',
    solution: 'l /bug<cr> n n n fE',
    par: 8, limit: 20,
  },
  {
    name: 'THE FINAL REFACTOR',
    // pinned to the index it had when its routes were authored — insertions
    // before it must not reshuffle the mage's dice
    seed: 12,
    teaches: 'everything — and a merciless budget',
    intro: [
      'No new tricks. No slack in the budget.',
      'Two wings, one vault, a mage with opinions.',
      'The vault tile runs a scan head. Never end a stroke under it.',
      'Golf it. Every keystroke is ammunition.',
    ],
    map: [
      '###############',
      '#P~~vim~~~goT.#',
      '#############V#',
      '#...ax~~byIZ<.#',
      '#.##%##########',
      '#.##*##########',
      '#*##*##########',
      '#.##.T.....E###',
      '#.#########^.##',
      '#..M.T..&...*.#',
      '###############',
    ],
    terminals: {
      '12,1': { broken: 'b0mB', target: 'bomb', grants: 2, hint: 'l ro  2l ~' },
      '5,9': { broken: 'rusty', target: 'bomb', grants: 1, hint: 'ciw bomb Esc' },
      '5,7': { kind: 'spark', broken: 'o......o', deadline: 8, grants: 1, hint: 'h grabs, $ finishes — don\'t camp' },
    },
    bushes: {
      '4,5': { type: 'U', amt: 1 },
      '4,6': { type: 'K', amt: 6 },
      '1,6': { type: 'R', amt: 1 },
      '12,9': { type: 'U', amt: 1 },
    },
    enemyOpts: { '10,3': { leash: 'row' }, '11,3': { leash: 'row' } },
    hint: 'north wing drills. south wing edits beside the mage. both work.',
    solution: 'w w ll i l ro 2l ~ l j j h 2b k x 2h h j k j k 3l 2j j j 7l',
    par: 36, limit: 60,
  },
  {
    name: 'BABY STEPS, PROMOTED',
    teaches: 'worn keys — lead with a count',
    intro: [
      'The first maze again. You are senior now, and the keys are',
      'worn smooth: a bare tap of h j k or l does NOTHING.',
      'Lead every motion with a number. Conviction registers.',
      'Twenty-eight keystrokes. The maze has not gotten longer. You have.',
    ],
    map: [
      '#############',
      '#P....#.....#',
      '#.###.#.###.#',
      '#.#...#...#.#',
      '#.#.#####.#.#',
      '#.#.....#.#.#',
      '#.###.#.#.#.#',
      '#*....#...#E#',
      '#############',
    ],
    terminals: {},
    bushes: { '1,7': { type: 'K', amt: 10 } },
    banned: ['h', 'j', 'k', 'l'],
    hint: 'the same maze, counted. twelve commands is the whole walk.',
    solution: '6j 4l 2k 2l 2j 2l 2k 2k 2h 2k 4l 6j',
    par: 24, limit: 28,
  },
  {
    name: 'AUTOMATE YOURSELF',
    teaches: 'q @ — record and replay',
    intro: [
      'q then a letter records. q stops. @ letter replays the lot —',
      'and the whole replay is ONE turn. The world barely notices.',
      'Three identical wings. The linters have learned your rhythm.',
      'Record the first wing by hand. Ship the other two.',
    ],
    map: [
      '#####################',
      '#P..#.....#.....#..E#',
      '###.#.###.#.###.#.###',
      '##!.*.##!.*.##!.*.###',
      '#####################',
    ],
    terminals: {},
    bushes: {
      '4,3': { type: 'K', amt: 4 },
      '10,3': { type: 'K', amt: 4 },
      '16,3': { type: 'K', amt: 4 },
    },
    linters: { '2,3': {}, '8,3': { phase: 3 }, '14,3': { phase: 4 } },
    keycaps: { '2,1': 'macro' },
    hint: 'the sweep cannot hit what has already left. one turn per wing.',
    solution: 'l qa l 2j 2l 2k 3l q @a @a',
    par: 14, limit: 26,
  },
];
